name: jaguar_cli
version: 0.0.28
description: Command line tool for jaguar-dart
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

executables:
  jaguar:

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  jaguar_generator: '>=0.7.1 <0.8.0'
  jaguar_serializer: '>=0.3.6 <0.4.0'
  jaguar_validate: '>=0.0.11 <0.1.0'
  jaguar_orm: '>=0.1.2 <0.2.0'
  args: ^0.13.7
  console: ^2.2.3
  build_runner: '>=0.3.4 <0.4.0'
  build: '>=0.9.3 <0.10.0'
  yaml: ">=2.1.10 <3.0.0"
  inflection: '>=0.4.1 <0.5.0'
  github: '>=3.0.0 <4.0.0'
  archive: '>=1.0.27 <2.0.0'
  http: '^0.11.3'
  path: '>=1.4.1 <2.0.0'
  source_gen: ^0.5.10+1

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
