name: jaguar_cli
version: 2.1.1
description: Command line tool for jaguar-dart
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar/wiki

executables:
  jaguar:

environment:
  sdk: ">=2.0.0-dev.65.0 <3.0.0"

dependencies:
  args: ^1.4.3
  console: ^3.0.0
  archive: ^2.0.0
  http: ^0.11.3
  path: ^1.6.1
  quiver: ^0.29.0

dev_dependencies:
  test: ^1.2.0
